BD103's Page (WIP)
Repl-it-Coders/About-Page pull request #2
Opened 2021-02-08 14:42 UTC by BD103

Don't merge yet, uwu.

(This is my page on the website!)

2021-02-08 16:18 UTC, whippingdot commented
Is this done? Should I review the changes yet or...

2021-02-08 16:57 UTC, darkdarcool requested changes
Looks good to me! You might wanna make the css a bit more tidy, like making two indentations for each changed thing, l made comment on what to change.

2021-02-08 16:57 UTC, darkdarcool commented on views/BD103.html
> +  </style>
Please make this a but tidier by adding two indentations for each css element like this:

``` css
body {
      font-family: "Montserrat", sans-serif;
      font-size: 20px;
      background: linear-gradient(to bottom right, darkcyan, lightcyan);
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: fixed;
    }
    h1, h2 {font-family: "Pangolin", cursive;}
        .title {font-size: 60px;}
        .center {text-align: center;}
        .left {text-align: left;}
        .right {text-align: right;}
  
```
Please update that.

2021-02-09 02:47 UTC, whippingdot requested changes
Added many reviewing comments and gave suggestions. You can change the CSS file(tho be careful as there will be merge conflicts) and you can change the index and signup pages(if the new tab thing is still there).

2021-02-09 02:47 UTC, whippingdot commented on views/BD103.html
> +  </style>
Umm sorry, I also have a problem with this. I already said that you should put your CSS in the style.css file(I even deleted everyone's files earlier cause they didn't do that). It is tidier that way. What I told everyone is to put a class on their HTML tag, ex. `<HTML class="bd">`, and then in the style.css file they can create a section for themselves, with comments, and for the CSS properties we could have:
```html
.bd body {
      font-family: "Montserrat", sans-serif;
      font-size: 20px;
      background: linear-gradient(to bottom right, darkcyan, lightcyan);
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: fixed;
 }
.bd h1, h2 {font-family: "Pangolin", cursive;}
.bd .title {font-size: 60px;}
.bd .center {text-align: center;}
.bd .left {text-align: left;}
.bd .right {text-align: right;}
```
And you could add the @import font thing at the top of the file with the other ones.

2021-02-09 02:47 UTC, whippingdot commented on views/BD103.html
>  <head>
Above this where the HTML tag is put the `<html class="bd">`

2021-02-09 02:47 UTC, whippingdot commented on views/BD103.html
> +  <p class="right">I started my programming career in 2017.</p>
Thanks for ending the redirect, it was horrible. The content of the page is fine for now I think, but maybe add more to the p element like what languages you know, and stuff like that. Also you can just link accounts from stuff like dev.to too. Also, if you are not redirecting, maybe making it open in a new page **_should_** be removed if not done already.

2021-02-10 14:53 UTC, BD103 commented
Bruh I'm not done yet.

2021-02-10 14:54 UTC, BD103 commented
Please wait for review until this PR does not have the WIP title or is not a draft.

2021-02-16 08:54 UTC, whippingdot commented
Hey @BD103 I don't wanna be impatient but what is the status on this? Doesn't seem like you have made any changes since I reviewed last time. If you meant to commit, please do.

2021-02-16 14:05 UTC, BD103 commented
Oooo yeah, got it.

2021-02-25 06:37 UTC, whippingdot commented
hey this is the only thing left

2021-02-25 12:22 UTC, darkdarcool requested changes
Maybe add a bit more about yourself as a coder.

2021-02-26 12:57 UTC, BD103 commented
> Maybe add a bit more about yourself as a coder.

Still a draft, please just give me time.

2021-02-26 15:22 UTC, darkdarcool commented
Ok. I just left my review when requested.

2021-02-26 16:16 UTC, whippingdot commented
@BD103 sry do it asap. Ima share now if i have time but if not till tomorrow

2021-02-26 17:39 UTC, darkdarcool commented
@BD103 kk. Just add it to the repl. Ima close this pull for now tho.

2021-02-26 17:39 UTC, closed without merging